#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
alias ls='ls --color=auto'
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Debian/Ubuntu

alias acs='apt-cache search'
alias afs='apt-file search --regexp'

# These are apt-get only
alias ags='apt-get source'
alias acp='apt-cache policy'

# superuser operations
alias afu='sudo apt-file update'
alias ppap='sudo ppa-purge'
alias ag='sudo apt-get'
alias aga='sudo apt-get autoclean'
alias agar='sudo apt-get autoremove'
alias agb='sudo apt-get build-dep'
alias agc='sudo apt-get clean'
alias agd='sudo apt-get dselect-upgrade'
alias agi='sudo apt-get install'
alias agp='sudo apt-get purge'
alias agr='sudo apt-get remove'
alias agu='sudo apt-get update'
alias agud='sudo apt-get update && sudo apt-get dist-upgrade'
alias agug='sudo apt-get upgrade'
alias aguu='sudo apt-get update && sudo apt-get upgrade'
alias agar='sudo apt-get autoremove'

# Android
export PATH=${PATH}:/home/kent/android-studio/sdk/tools
export PATH=${PATH}:/home/kent/android-studio/sdk/platform-tools

# Miscellanous
alias meteo='curl wttr.in/'

alias c='clear'

function mcd() {
  mkdir -p "$1" && cd "$1";
}

function ssh_tmux() { ssh -t "$1" tmux a || ssh -t "$1" tmux; }
